### ISSUE TITLE
No kernel image is available for execution on the device in Emgu CV 4.5.3 Release

### ISSUE THREAD

**Issue by kumartest1981** [emgucv/emgucv#578]
### Discussed in https://github.com/emgucv/emgucv/discussions/577

<div type='discussions-op-text'>

<sup>Originally posted by **kumartest1981** September  6, 2021</sup>

We are trying to run the sample code (libemgucv-windesktop_x64-cuda-4.5.3.4721.exe) but we are getting the following error. We are running on Tesla V100 (azure machine) with cuda 11.1 and cudnn 8.0.5. Can you please help us to resolve the issue

Driver Name: Nvidia Telsa V100-PCIE-16GB
Driver Version: 471.41
Operation System: Windows Server 2016 Datacenter

**Code snippet :**
Mat matImage = sourceBM;               
Size newSize = new Size(width, height);
CudaImage<Bgr, Byte> cudaImg = new CudaImage<Bgr, Byte>(matImage);
CudaImage<Bgr, Byte> cudaImgRsz = cudaImg.Resize(newSize, Inter.Nearest);

**Error Message:**
  
  Unhandled exception. Emgu.CV.Util.CvException: OpenCV: no kernel image is available for execution on the device
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.Cuda.CudaInvoke.cudaResize(IntPtr src, IntPtr dst, Size& dsize, Double fx, Double fy, Inter interpolation, IntPtr stream)
   at Emgu.CV.Cuda.CudaInvoke.Resize(IInputArray src, IOutputArray dst, Size dsize, Double fx, Double fy, Inter interpolation, Stream stream)
   at Emgu.CV.Cuda.CudaImage`2.Resize(Size size, Inter interpolationType, Stream stream)
   at ConsoleApp2.Program.ResizeImage(String imageName, String pathToImages, Int32 width, Int32 height, Boolean usingCuda) in 

</div>

**Comment by emgucv** [comment]
The official Emgu CV 4.5.3 cuda release is build with CUDA_ARCH_BIN_OPTION of "5.2 6.1 7.5 8.6". Tesla V100 is compute "7.0" device and is not compatible with our CUDA_ARCH_BIN_OPTION. 

If you want to use Emgu CV with Tesla v100, you can recompile Emgu CV with CUDA following this instruction:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Building_from_Git 

Depends on the CUDA SDK version you install, you will need to change this script here:
https://github.com/emgucv/emgucv/blob/4.5.3/platforms/windows/Build_Binary_x86.bat#L458
and include "7.0"  to CUDA_ARCH_BIN_OPTION.

**Comment by emgucv** [comment]
I have updated the build script in master to include compute 7.0:
https://github.com/emgucv/emgucv/commit/a7ac2f304fcb911f6a4133a5f6ea8bbf84d5d8cd

The next relase should be able to run on Tesla V100. The final binary will be bigger (7 architectures instead of 4), the part of binary related to CUDA will be 75% bigger.

**Comment by emgucv** [comment]
This was fixed after the 4.5.3 release. CUDA compute 7.0 (Tesla V100) was added to the `CUDA_ARCH_BIN` build options in commit a7ac2f304 and has been included in all subsequent releases. The current Emgu CV CUDA builds support Tesla V100 out of the box. Closing now.
